### ISSUE TITLE
Why hide the sequence number and partition key from consumers?

### ISSUE THREAD

**Issue by gmalouf** [gilt/gfc-kinesis#6]
I can imagine this being very useful for end users (us included in this).  It would be cool if there was an option when signing up to 'consume' that allowed passing a function which accepts this data when converting.  

The raw api is fine for now, but this would be cool.

**Comment by conorclifford** [comment]
The intention was to keep the typed API as simple as possible, but there is indeed value in passing both partition-key and sequence numbers. I'm going to look at adding both. Thanks!

**Comment by conorclifford** [comment]
Updated typed consumer API to expose partition-key (https://github.com/gilt/gfc-kinesis/commit/8d903c5381b1da987bbbe58caa797ddcabbc0689) and sequence-number (https://github.com/gilt/gfc-kinesis/commit/aa5366f69401995dd4f2d8cb4ce33f4a091c5c83) to client applications.

**Comment by gmalouf** [comment]
Awesome!  Thank you!
