### ISSUE TITLE
Make retry logging 'WARN' level rather than 'ERROR'

### ISSUE THREAD

**Issue by gmalouf** [gilt/gfc-kinesis#9]
When a publish attempt fails, the RetryingStreamPublisher is used to make more attempts to send the data along.  For each failure, an 'ERROR' level message gets logged.  From using other clients and for error detecting reasons, I think it makes more sense to have this logging be at the 'WARN' level.

https://github.com/gilt/gfc-kinesis/blob/master/src/main/scala/com/gilt/gfc/kinesis/publisher/RawKinesisStreamPublisher.scala#L125

Ideally, once the retry attempts have been exhausted without success, an error would be logged.

**Comment by Seanstoppable** [comment]
Any reason not to use gfc's retry able?

https://github.com/gilt/gfc-util/blob/master/src/main/scala/com/gilt/gfc/util/Retry.scala

Already handles non-fatal exceptions by just retrying, where a fatal (either stopped retrying, or some other fatal exception) actually causes an exception to be thrown.

**Comment by gmalouf** [comment]
Are you suggesting to wrap the KinesisMessagePublisher (which has it's own
retry capabilities) inside of that retryable?   Or, are you suggesting to
fork the project and update the publisher to use the gfc retry able?

Current usage:

val mp = RawKinesisStreamPublisher(kinesisStream, config)
.
.
.
.

mp.putRecord(rawRecord)


The putRecord call uses the current, internal retry logic.

**Comment by gheine** [comment]
I think it's the async retry in
https://github.com/gilt/gfc-concurrent/blob/master/src/main/scala/com/gilt/gfc/concurrent/ScalaFutures.scala#L158
that this should be replaced with.

**Comment by gmalouf** [comment]
@gheine agreed, that is what I am thinking

**Comment by gmalouf** [comment]
Rather than add a new dependency to the project, does copy/pasting make more sense here?

**Comment by gmalouf** [comment]
Closing this since the issue was resolved in https://github.com/gilt/gfc-kinesis/pull/10
